Monter le lecteur Drive où sont stockées les données

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Lire les données du CSV

In [5]:

import pandas as pd
#  Load a CSV file from your Drive
df = pd.read_csv('/content/drive/MyDrive/eco2mix-regional-cons-def.csv', sep=';')

/tmp/ipykernel_4608/1768945194.py:3: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/eco2mix-regional-cons-def.csv', sep=';')

lire les première lignes

In [6]:
df.head()

,Code INSEE région,Région,Nature,Date,Heure,Date - Heure,Consommation (MW),Thermique (MW),Nucléaire (MW),Eolien (MW),...,TCH Nucléaire (%),TCO Eolien (%),TCH Eolien (%),TCO Solaire (%),TCH Solaire (%),TCO Hydraulique (%),TCH Hydraulique (%),TCO Bioénergies (%),TCH Bioénergies (%),Column 30
0,76,Occitanie,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,53,Bretagne,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,27,Bourgogne-Franche-Comté,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,84,Auvergne-Rhône-Alpes,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,32,Hauts-de-France,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

import des librairies panda et numpy

In [7]:
import pandas as pd
import numpy as np

afficher les types de chaque variable de données

In [8]:
df.dtypes

Code INSEE région        int64
Région                  object
Nature                  object
Date                    object
Heure                   object
Date - Heure            object
Consommation (MW)      float64
Thermique (MW)         float64
Nucléaire (MW)         float64
Eolien (MW)             object
Solaire (MW)           float64
Hydraulique (MW)       float64
Pompage (MW)           float64
Bioénergies (MW)       float64
Ech. physiques (MW)    float64
Stockage batterie      float64
Déstockage batterie    float64
Eolien terrestre       float64
Eolien offshore        float64
TCO Thermique (%)      float64
TCH Thermique (%)      float64
TCO Nucléaire (%)      float64
TCH Nucléaire (%)      float64
TCO Eolien (%)         float64
TCH Eolien (%)         float64
TCO Solaire (%)        float64
TCH Solaire (%)        float64
TCO Hydraulique (%)    float64
TCH Hydraulique (%)    float64
TCO Bioénergies (%)    float64
TCH Bioénergies (%)    float64
Column 30              float64
dtype: object

Affichage du nombre de lignes et de colonnes du data frame

In [9]:
df.shape

(2803968, 32)